In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np


In [19]:
import seaborn as sns 
df = sns.load_dataset("iris")
df.head()

sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [20]:
df[47:52 ]

sepal_length  sepal_width  petal_length  petal_width     species
47           4.6          3.2           1.4          0.2      setosa
48           5.3          3.7           1.5          0.2      setosa
49           5.0          3.3           1.4          0.2      setosa
50           7.0          3.2           4.7          1.4  versicolor
51           6.4          3.2           4.5          1.5  versicolor

In [4]:
x = df.iloc[: , :-1]
y = df.iloc[: , -1]


In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3, random_state = 101)

# SVM CLASSIFICATION

In [6]:
from sklearn import svm

In [7]:
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf' , random_state=1, C=30, gamma='auto')
classifier.fit(x_train, y_train)
classifier.score(x_test,y_test)

0.9777777777777777

# K CROSS VALIDATION

In [8]:
from sklearn.model_selection import cross_val_score

In [9]:
cross_val_score(svm.SVC(kernel='linear', C=10, gamma='auto'),x,y,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [10]:
cross_val_score(svm.SVC(kernel='rbf', C=10, gamma='auto'),x,y,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [11]:
cross_val_score(svm.SVC(kernel='rbf', C=20, gamma='auto'),x,y,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

### same thing using a loop

In [12]:
kernels = ['rbf', 'linear']
C = [1,10,20]
avg_scores = {}
for kval in kernels:
  for cval in C:
    cv_scores = cross_val_score(svm.SVC(kernel=kval,C=cval, gamma='auto'),x,y,cv=5)
    avg_scores[kval+'_'+str(cval)]=np.average(cv_scores)
avg_scores

{'linear_1': 0.9800000000000001,
 'linear_10': 0.9733333333333334,
 'linear_20': 0.9666666666666666,
 'rbf_1': 0.9800000000000001,
 'rbf_10': 0.9800000000000001,
 'rbf_20': 0.9666666666666668}

# GRID SEARCH CV

In [13]:
from sklearn.model_selection import  GridSearchCV
parameters = {
    'kernel':('linear', 'rbf'), 
    'C':[1, 20]
    }
svc = svm.SVC()



In [14]:
clf = GridSearchCV(svc, parameters)


In [15]:
clf.fit(x_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=SVC(C=1.0, break_ties=False, cache_size=200,
                           class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='scale', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1, 20], 'kernel': ('linear', 'rbf')},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [16]:
print(clf.best_params_)

{'C': 1, 'kernel': 'linear'}


In [18]:
df2 = pd.DataFrame(clf.cv_results_)
df2

mean_fit_time  std_fit_time  ...  std_test_score  rank_test_score
0       0.002485      0.000722  ...        0.038095                1
1       0.001531      0.000076  ...        0.042592                2
2       0.001447      0.000121  ...        0.055533                4
3       0.001455      0.000038  ...        0.042592                2

[4 rows x 15 columns]

In [21]:
df2[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1       linear         0.971429
1       1          rbf         0.952381
2      20       linear         0.942857
3      20          rbf         0.952381

In [22]:
dir(clf)

['__abstractmethods__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_abc_cache',
 '_abc_negative_cache',
 '_abc_negative_cache_version',
 '_abc_registry',
 '_check_is_fitted',
 '_estimator_type',
 '_format_results',
 '_get_param_names',
 '_get_tags',
 '_more_tags',
 '_pairwise',
 '_required_parameters',
 '_run_search',
 'best_estimator_',
 'best_index_',
 'best_params_',
 'best_score_',
 'classes_',
 'cv',
 'cv_results_',
 'decision_function',
 'error_score',
 'estimator',
 'fit',
 'get_params',
 'iid',
 'inverse_transform',
 'multimetric_',
 'n_jobs',
 'n_splits_',
 'param_grid',
 'pre_dispatch',
 'predict',
 'predict_log_proba',

In [23]:
clf.best_score_

0.9714285714285715

In [24]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

## CHOOSING MODEL

In [25]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression


In [28]:
model_params = {
    'svm':{
        'model': svm.SVC(gamma='auto'),
        'params': {
            'C':[1,10,20],
            'kernel': ['rbf', 'linear']
        }
    },
    'random_forest':{
        'model':RandomForestClassifier(),
        'params':{
            'n_estimators':[1,5,10]
        }
    },
    'logistic_regression':{
        'model': LogisticRegression(solver='liblinear', multi_class='auto'),
        'params':{
            'C' : [1,5,10]
        }
    }
}


In [29]:
scores = []
for model_name, mp in model_params.items():
  clff = GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
  clff.fit(x,y)
  scores.append({
      'model':model_name,
      'best_score': clff.best_score_,
      'best_params': clff.best_params_
  })

In [30]:
df3 = pd.DataFrame(scores, columns=['model', 'best_score' , 'best_params'])
df3

model  best_score                best_params
0                  svm    0.980000  {'C': 1, 'kernel': 'rbf'}
1        random_forest    0.960000        {'n_estimators': 5}
2  logistic_regression    0.966667                   {'C': 5}